apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 1.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: infra              # 沿用 infra,不自己建(交給 namespaces App)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true